name: Run Cypress with Allure

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  e2e-allure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Restore Allure history
        uses: actions/download-artifact@main
        with:
          name: allure-history
          path: allure-results/history
        continue-on-error: true

      - name: Run Cypress tests
        run: npx cypress run --env allure=true

      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Copy report history for next builds
        run: |
          mkdir -p allure-results/history
          cp -r allure-report/history/* allure-results/history/ || echo "No history to copy"

      - name: Save Allure history
        uses: actions/upload-artifact@main
        with:
          name: allure-history
          path: allure-report/history

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@main
        with:
          name: allure-report
          path: allure-report

          