name: Cypress Tests with Allure

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: write # ✅ Permite hacer push a gh-pages desde el bot

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Restore Allure History
        uses: actions/download-artifact@v4.2.1
        continue-on-error: true
        with:
          name: allure-history
          path: allure-results/history

      - name: Run Cypress tests with Allure
        run: npx cypress run --env allure=true
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

      - name: Generate Allure report
        run: npx allure generate allure-results --clean -o allure-report

      - name: Copy report history for next builds
        run: |
          mkdir -p allure-results/history
          cp -r allure-report/history/* allure-results/history/ || echo "No history to copy"

      - name: Save Allure History
        uses: actions/upload-artifact@v4.6.2
        with:
          name: allure-history
          path: allure-report/history

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: allure-report
          path: allure-report

      # 🔥 Despliegue automático a GitHub Pages
      - name: Deploy Allure Report to GitHub Pages 🚀
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
